question_data = [
        {
            "category": "Mythology",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In Norse mythology, Thor once dressed as a woman.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The song &quot;Megalovania&quot; by Toby Fox made its third appearence in the 2015 RPG &quot;Undertale&quot;.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Geography",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Vatican City is a country.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Art",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Leonardo da Vinci&#039;s Mona Lisa does not have eyebrows.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Music",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Eurobeat is primarily an Italian genre of music.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In &quot;Mario Kart 64&quot;, Waluigi is a playable character.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Politics",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The S in Harry S. Truman stands for &quot;Samuel&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Books",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The &quot;Berenstein Bears&quot; is the correct spelling of the educational children&#039;s book series&#039; name.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Big the Cat is a playable character in &quot;Sonic Generations&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Bulls are attracted to the color red.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Tetris is the #1 best-selling video game of all-time.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Ada Lovelace is often considered the first computer programmer.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Cartoon & Animations",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Bill Cipher in the show &quot;Gravity Falls&quot; is the good guy.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Politics",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Shaquille O&#039;Neal appeared in the 1997 film &quot;Space Jam&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The color orange is named after the fruit.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "easy",
            "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the &quot;Half-Life&quot; series, &quot;H.E.V&quot; stands for &quot;Hazardous Evasiveness Vest&quot;",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Pluto is a planet.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "When you cry in space, your tears stick to your face.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In Terraria, you can craft the Cell Phone pre-hardmode.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "easy",
            "question": "An Astronomical Unit is the distance between Earth and the Moon.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Music",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Daft Punk originated in France.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Klingons express emotion in art through opera and poetry.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Activision created Battlefield 1.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The National Animal of Scotland is the Unicorn.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Geography",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Nova Scotia is on the east coast of Canada.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars manufactured by Porsche.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Mathematics",
            "type": "boolean",
            "difficulty": "easy",
            "question": "An isosceles triangle has two sides of equal length as opposed to three.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Slovakia is a member of European Union-",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "easy",
            "question": "There are a total of 20 races in Formula One 2016 season.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Doki Doki Literature Club was developed in Japan.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In &quot;Space Station 13&quot;,  the station has a clown aboard it.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        }
]